name: Run tests

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**/*.md"
  pull_request:

jobs:
  run-tests-for-all-combinations:
    uses: ./.github/workflows/build-artifacts-and-run-tests.yml
